source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'rails', '~> 6.0.1'
gem 'puma', '~> 4.1'
gem 'bootsnap', '>= 1.4.2', require: false

gem 'mysql2'

group :development do
  gem "spring"
  gem "annotate"

  gem "web-console", ">= 3.3.0"
  gem "better_errors"
  gem "binding_of_caller"
end
