# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "gbailey/amzn2"
  config.vm.box_check_update = true
  config.vm.network :private_network, type: :dhcp
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  config.vm.provision :shell, inline: <<-SHELL
    yum update -y
    mkdir -m 700 /etc/skel/.ssh
    useradd -G wheel admin
    echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel-group
    cat > /home/admin/.ssh/authorized_keys << EOF
    #{File.read("#{Dir.home}/.ssh/id_rsa.pub")}
EOF
    ip addr
  SHELL
end
